#ifndef BRAINCUNT_APP_VERSION_H
#define BRAINCUNT_APP_VERSION_H

#define BRAINCUNT_VERSION						0x000202
#define BRAINCUNT_VERSION_MAJOR					0
#define BRAINCUNT_VERSION_MINOR					2
#define BRAINCUNT_VERSION_SUBMINOR				1
#define BRAINCUNT_VERSION_BUILD					2
#define BRAINCUNT_MESSAGE						"Playing with my brain!"
#define BRAINCUNT_EXIT_MESSAGE					"Thank you for enjoying my brain ..."

#define BRAINCUNT_STRINGIZE_I(TEXT)				#TEXT
#define BRAINCUNT_STRINGIZE(TEXT)				BRAINCUNT_STRINGIZE_I(TEXT)

#define BRAINCUNT_VERSION_STRING				BRAINCUNT_STRINGIZE(BRAINCUNT_VERSION_MAJOR.BRAINCUNT_VERSION_MINOR.BRAINCUNT_VERSION_SUBMINOR.BRAINCUNT_VERSION_BUILD)

#endif	// #ifndef BRAINCUNT_APP_VERSION_H
