#ifndef BRAINCUNT_VERSION_H
#define BRAINCUNT_VERSION_H

#include <WinVer.h>
#include "app_version.h"

#define BRAINCUNT_PROJECT_NAME					"Braincunt"
#define BRAINCUNT_MODULE_NAME					"Braincunt"

#define BRAINCUNT_RC_PROJECT_NAME				BRAINCUNT_PROJECT_NAME
#define BRAINCUNT_RC_MODULE_NAME				BRAINCUNT_MODULE_NAME

#define BRAINCUNT_RC_VERSION_MAJOR				BRAINCUNT_VERSION_MAJOR
#define BRAINCUNT_RC_VERSION_MINOR				BRAINCUNT_VERSION_MINOR
#define BRAINCUNT_RC_VERSION					BRAINCUNT_VERSION_MAJOR,BRAINCUNT_VERSION_MINOR,BRAINCUNT_VERSION_SUBMINOR,BRAINCUNT_VERSION_BUILD

#define BRAINCUNT_FULL_PROJECT_NAME				BRAINCUNT_RC_PROJECT_NAME
#define BRAINCUNT_FULL_MODULE_NAME				BRAINCUNT_RC_MODULE_NAME

#define BRAINCUNT_FILEVERSION					BRAINCUNT_RC_VERSION
#define BRAINCUNT_PRODUCTVERSION				BRAINCUNT_RC_VERSION
#define BRAINCUNT_FILEFLAGSMASK					VS_FFI_FILEFLAGSMASK
#define BRAINCUNT_FILEFLAGS						(0x0L | VS_FF_PRERELEASE)
#define BRAINCUNT_FILEOS						VOS_NT_WINDOWS32
#define BRAINCUNT_FILETYPE						VFT_DLL
#define BRAINCUNT_FILESUBTYPE					VFT2_UNKNOWN

#define BRAINCUNT_COMMENTS						BRAINCUNT_FULL_MODULE_NAME \
												" " BRAINCUNT_VERSION_STRING \
												" (" BRAINCUNT_MESSAGE ")" \
												"\0"
#define BRAINCUNT_COMPANY_NAME					"Boleros\0"
#define BRAINCUNT_FILE_DESCRIPTION				BRAINCUNT_FULL_MODULE_NAME " (Interpreter Engine)\0"
#define BRAINCUNT_FILE_VERSION					BRAINCUNT_STRINGIZE(BRAINCUNT_RC_VERSION) "\0"
#define BRAINCUNT_INTERNAL_NAME					BRAINCUNT_FULL_PROJECT_NAME "\0"
#define BRAINCUNT_LEGAL_COPYRIGHT				"Copyright (C) 2010-2011 Boleros.\0"
#define BRAINCUNT_LEGAL_TRADEMARKS				"\0"
#define BRAINCUNT_ORIGINAL_FILENAME				BRAINCUNT_FULL_PROJECT_NAME ".exe\0"
#define BRAINCUNT_PRODUCT_NAME					BRAINCUNT_FULL_MODULE_NAME "\0"
#define BRAINCUNT_PRODUCT_VERSION				BRAINCUNT_STRINGIZE(BRAINCUNT_RC_VERSION) "\0"
#define BRAINCUNT_PRIVATE_BUILD					"\0"
#define BRAINCUNT_SPECIAL_BUILD					"\0"

#endif	// #ifndef BRAINCUNT_VERSION_H
